List<List<String>> itemList = [
  ["fruit", "Apple", "Banana", "Orange"],
  ["colors", "Red", "Green", "Blue"],
  ["vehicle", "Car", "Bike", "Truck"],
  ["country", "USA", "Japan", "France"],
  ["animal", "Dog", "Cat", "Elephant"],
  ["shape", "Circle", "Triangle", "Square"],
  ["flower", "Rose", "Sunflower", "Tulip"],
  ["instrument", "Piano", "Guitar", "Violin"],
  ["food", "Pizza", "Burger", "Sushi"],
  ["sport", "Football", "Basketball", "Tennis"],
  ["movie", "Titanic", "Inception", "The Matrix"],
  ["book", "Harry Potter", "To Kill a Mockingbird", "1984"],
  ["city", "New York", "Tokyo", "Paris"],
  ["planet", "Earth", "Mars", "Jupiter"],
  ["profession", "Doctor", "Engineer", "Teacher"],
  ["drink", "Coffee", "Tea", "Juice"],
  ["clothing", "Shirt", "Pants", "Dress"],
  ["weather", "Sunny", "Rainy", "Snowy"],
  ["language", "English", "Spanish", "Chinese"],
  ["holiday", "Christmas", "Halloween", "Easter"],
  // Add more items as needed
];
